# Generated by Django 5.0.2 on 2024-03-29 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbrands', '0003_comment'),
        ('user', '0003_remove_buycar_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buycar',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbrands.car'),
        ),
    ]
