# Generated by Django 5.0.2 on 2024-03-29 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_buycar_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuyCar',
        ),
    ]
